#!/bin/sh
set -eu

cat > /usr/share/nginx/html/env.js << EOF
window.__ENV__ = {
  VITE_SPOTIFY_CLIENT_ID: "${VITE_SPOTIFY_CLIENT_ID:-}",
  VITE_SPOTIFY_CLIENT_SECRET: "${VITE_SPOTIFY_CLIENT_SECRET:-}",
  VITE_SPOTIFY_REDIRECT_URI: "${VITE_SPOTIFY_REDIRECT_URI:-}",
  VITE_TRACKWATCH_API_BASE_URL: "${VITE_TRACKWATCH_API_BASE_URL:-/api}",
  VITE_HIDE_PUBLIC_LOGIN: "${VITE_HIDE_PUBLIC_LOGIN:-false}"
};
EOF

exec "$@"
