ARTISTS = [
  "Bad Bunny",
  "Milo j",
  "Duki",
  "JHAYCO",
  "Rauw Alejandro",
  "Anuel AA",
  "Myke Towers",
  "Feid",
  "Quevedo",
  "Eladio Carrion",
  "Tainy",
  "J Balvin",
  "Bizarrap",
  "YSY A",
  "KHEA",
  "Alvaro Diaz",
  "Arcangel",
  "Blessd",
  "Neo Pistea",
  "Rels B",
  "Kris R.",
  "Omar Courtz",
  "Brray",
  "Judeline",
  "Mora",
  "Ryan Castro",
  "Cruz Cafuné",
  "Young Miko",
  "Travis Scott",
  "Dei V",
  "Luar La L",
  "YOVNGCHIMI",
  "C Tangana",
  "Rosalia",
  "Peso Pulma",
  "Natanael Cano",
  "Gorillaz",
  "SAIKO",
  "Sky Rompiendo",
  "Kendrick Lamar",
  "Drake",
  "Twenty One Pilots",
  "The Weeknd",
  "Tame Impala",
  "LIT Killah",
  "Billie Eilish",
  "Post Malone",
  "Dua Lipa",
  "De La Rose",
  "Raul Clyde",
  "C.R.O",
  "Nicki Nicole",
  "LATIN MAFIA",
  "W Sound",
  "Maluma",
  "Trueno",
  "Karol G",
  "Hades66",
  "Dillom",
  "Paulo Londra",
  "Sech",
  "De La Ghetto",
  "De La Rose",
  "RaiNao",
  "Cris Mj",
  "Yandel",
  "Don Omar",
]