# Generated by Django 5.2.1 on 2025-06-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_userfollowedartist_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="updates_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
