# Generated by Django 5.2.1 on 2026-01-30 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_updates_enabled"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFollowedArtist",
        ),
    ]
