# Generated by Django 5.2.14 on 2026-06-28 21:46

from django.db import migrations, models


def populate_existing_spotify_authorizations(apps, schema_editor):
    User = apps.get_model("app", "User")
    User.objects.filter(
        spotify_authorized_at__isnull=True,
    ).exclude(
        current_refresh_token="",
    ).update(
        spotify_authorized_at=models.F("date_joined"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_delete_userfollowedartist"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="spotify_authorized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="spotify_reauth_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            populate_existing_spotify_authorizations,
            migrations.RunPython.noop,
        ),
    ]
